replicaCount: 1

# Environnement : dev, qa, staging ou prod
environment: dev

movieService:
  image: salim2025/movie-service
  tag: latest
  containerPort: 8000
  service:
    port: 8001
  env:
    - name: DATABASE_URI
      value: "postgresql://movie_db_username:movie_db_password@movie-db/movie_db_{{ .Values.environment }}"
    - name: CAST_SERVICE_HOST_URL
      value: "http://cast-service:8000/api/v1/casts/"

castService:
  image: salim2025/cast-service
  tag: latest
  containerPort: 8000
  service:
    port: 8002
  env:
    - name: DATABASE_URI
      value: "postgresql://cast_db_username:cast_db_password@cast-db/cast_db_{{ .Values.environment }}"

movieDB:
  image: postgres:12.1-alpine
  containerPort: 5432
  env:
    - name: POSTGRES_USER
      value: movie_db_username
    - name: POSTGRES_PASSWORD
      value: movie_db_password
    - name: POSTGRES_DB
      value: "movie_db_{{ .Values.environment }}"

castDB:
  image: postgres:12.1-alpine
  containerPort: 5432
  env:
    - name: POSTGRES_USER
      value: cast_db_username
    - name: POSTGRES_PASSWORD
      value: cast_db_password
    - name: POSTGRES_DB
      value: "cast_db_{{ .Values.environment }}"

nginx:
  image: nginx:latest
  containerPort: 8080
  service:
    port: 8080
  config:
    nginxConf: |
      server {
          listen 8080;
          server_name localhost;
          location / {
              proxy_pass http://movie_service:8000;
          }
      }

# Bloc de configuration global pour le service utilisé par certains templates
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Configuration du ServiceAccount
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Configuration de l'Ingress (ajouté pour éviter l'erreur dans le template ingress.yaml)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
